name: Build and Upload to SFTP

on:
  push:
    branches:
      - main
    paths:
      - 'pdf/**'
      - 'public/**'
      - 'src/**'
      - 'package.json'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the app
        run: |
          docker build . --target build -v $(pwd)/build:/build

      - name: SFTP Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "build/*"
          target: "/"
          rm: true # This will remove the files before uploading
