name: Build and Upload to SFTP

on:
  push:
    branches:
      - main
    paths:
      - 'pdf/**'
      - 'public/**'
      - 'src/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --target build -t rezepte.ttst.de/build .

      - name: Build App
        run: docker run -v ${{ github.workspace }}/build:/app/build rezepte.ttst.de/build

      - name: Upload to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: 'build'
          remote_path: '/'
          delete_remote_files: true
