name: Upload _REZEPTE_ to SFTP

on:
  push:
    branches:
      - main
    paths:
      - '_REZEPTE_/**'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: '_REZEPTE_'
          remoteDir: '_REZEPTE_'
          removeExtraFilesOnServer: true
