name: Upload _REZEPTE_ to SFTP

on:
  push:
    branches:
      - main
    paths:
      - '_REZEPTE_/**'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: '_REZEPTE_'
          remote_path: '_REZEPTE_'
          delete_remote_files: true
          sftp_only: true
